ADDITIONAL_BUILD_PROPERTIES += \
    ro.cygnus.build.version=$(LINEAGE_VERSION) \
    ro.cygnus.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.cygnus.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.modversion=$(CYGNUS_VERSION)

# Versioning
ANDROID_VERSION = 10
PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0
CYGNUS_VERSION = $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

# Official and Unofficial builds
ifndef CYGNUS_BUILD_TYPE
CYGNUS_BUILD_TYPE := UNOFFICIAL
endif

# Packaging
LINEAGE_VERSION := Cygnus-$(CYGNUS_VERSION)-$(shell date +%Y%m%d)-$(CYGNUS_BUILD_TYPE)_Android-$(ANDROID_VERSION)
LINEAGE_DISPLAY_VERSION := Cygnus-$(CYGNUS_VERSION)-$(CYGNUS_BUILD_TYPE)_Android-$(ANDROID_VERSION)
